apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "central-ingress.name" . }}-external
  labels:
    app: {{ template "central-ingress.name" . }}-external
    chart: {{ template "central-ingress.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- with .Values.ingress.external.annotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
spec:
  rules:
  {{- range .Values.ingress.external.hosts }}
    - host: {{ .hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: redirect
                port:
                  name: use-annotation
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .port }}
  {{- end }}
